pull_requests:
  do_not_increment_build_number: true

skip_tags: false
max_jobs: 1
skip_commits:
  files:
    - README.md
    - CHANGELOG.md
    - .editorconfig
    - .gitignore
    - renovate.json


image: ubuntu
stack: docker

init:
  - ps: ./scripts/init.ps1

build_script:
  - ps: ./scripts/build.ps1

test_script:
  - ps: ./scripts/test.ps1

deploy_script:
  - ps: ./scripts/deploy.ps1
