pull_requests:
  do_not_increment_build_number: true

skip_tags: true
max_jobs: 1
skip_commits:
  files:
    - README.md
    - CHANGELOG.md
    - .editorconfig
    - .gitignore


image: ubuntu
stack: docker

init:
  - git config --global core.autocrlf true

build_script:
  - docker build .

test: off
